blank_issues_enabled: true
contact_links:
  - name: Learn Earn & Fun Support
    email-id: hridayahoney@gmail.com
    about: Please ask and answer questions here.
  - name: Learn Earn & Fun Security Bug Bounty
    email-id: hridayahoney@gmail.com
    about: Please report security vulnerabilities here.
